### ISSUE TITLE
Problem installing scikit-monaco

### ISSUE THREAD

**Issue by alrortiz** [scikit-monaco/scikit-monaco#10]
Hello,

I have tried to install scikit-monaco in Python2.7 and it is reporting an issue.

I have tried: 

- pip install scikit-monaco:

Failed building wheel for scikit-monaco
LINK : fatal error LNK1181: cannot open input file 'm.lib'

- easy_install

 scikit_monaco: 

LINK : fatal error LNK1181: cannot open input file 'm.lib'

- I tried to install directly, this is what happened:

Unable to find vcvarsall.bat

I know that problem should be related to compiler, but another packages can install without problems.

Thank you,

Albert

**Comment by alrortiz** [comment]
I forgot to assign it to @pbugnion

**Comment by pbugnion** [comment]
I'll try and have a look at this, but, truth be told, this repository isn't really maintained at present. If you want to have a go at fixing this, I'm happy to accept pull requests.

**Comment by alrortiz** [comment]
Dear Pascal,


Thank you for the response.


I will appreciate if you could check the problem. I have tried without alter the code (just the installers) and it is not working.


I am in the final way of my PhD and I need to do some integrations!!!


Thank you,


Albert


------
Albert R. Ortiz Lasprilla
Graduate Research Assistant
Phone: (1) 803 - 800 25 29
Email: aro@email.sc.edu
Web: http://sdii.ce.sc.edu/user/103

Department of Civil and Environmental Engineering
University of South Carolina
Columbia, SC. USA


________________________________

**Comment by olefinic** [comment]
Hello @alrortiz,
I hope it is not too late to response. And I assume you were to use skmonaco on Windows.
To solve the installing problem:
     delete all 'libraries=["m"]' option in config.add_extension
     install from setup.py
as for the problem of vcvarsall.bat, I guess it's due to the version of your VS common tools and it might work if you just change the environment variable

**Comment by pbugnion** [comment]
@olefinic Thanks for looking into this. I don't have access to a Windows machine to test this out.

If you have time, could you paste the revised `skmonaco/setup.py` (or open a pull request)?

**Comment by olefinic** [comment]
@pbugnion Then I think it would influence the gcc users if delete 'libraries = ['m']' in such a simple way...⊙﹏⊙ 
Yes, indeed, having tested on OS X, I found skmonaco works well without any modification. The little trick is only for machine using vc, I guess.

**Comment by pbugnion** [comment]
Thanks for this. It'll definitely be useful for people wanting to use this on Windows!
