### ISSUE TITLE
MathJax is no longer working on the current build of the documentation

### ISSUE THREAD

**Issue by Naereen** [scikit-monaco/scikit-monaco#11]
Hi,
I'm not sure anyone is still able to maintain this project, but here I go.
On the documentation, MathJax is loaded from the now deprecated cdn.mathjax.org, and is loaded with `http://` and not `https://`. So long story short, the maths are not correctly displayed!
See for instance [this page](https://scikit-monaco.readthedocs.io/en/latest/tutorials/getting_started.html#complex-integration-volumes).

Thanks in advance if anyone can try to solve this.

**Comment by Naereen** [comment]
By the way, this issue even makes it impossible to load manually MathJax, as it can be done on other pages with tools like [mathjax-bookmarklet](https://naereen.github.io/mathjax-bookmarklet/).
See this issue: https://github.com/Naereen/mathjax-bookmarklet/issues/1

**Comment by Naereen** [comment]
And to finish, I see that MathJax is configured in the conf.py file like this
https://github.com/scikit-monaco/scikit-monaco/blob/1082e536c32a0b22ccc0dcc104878ddf9588fe7a/doc/source/conf.py#L33
I think if the doc is rebuilt, an up-to-date `sphinx.ext.mathjax` module will be used, with a correct URL for loading MathJax (e.g., `https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML`).

**Comment by pbugnion** [comment]
Thanks for raising this!

> I'm not sure anyone is still able to maintain this project, but here I go

No, this is basically unmaintained. If you're interested in pushing this fix through, I can add you to the organisation.

**Comment by Naereen** [comment]
Hi @pbugnion, OK.
Yeah sure, why not, if you can add me to the scikit-monaco organisation, but I guess I also need to have access to the readthedocs account/profile/whatever, in order to force an update of the doc (or is it enough to do a tiny commit?)

**Comment by pbugnion** [comment]
I've added you to the organisation. We should probably take this offline to avoid spamming this issue. I'll send you an email to the email address listed on the website linked to your GitHub account.

**Comment by Naereen** [comment]
:tada: Seems to be fixed, I just manually force a new build of the doc.
For example:
![fixed](https://user-images.githubusercontent.com/11994719/36558112-526504d8-180a-11e8-8f42-c804b18467c9.png)

**Comment by pbugnion** [comment]
Great! Thank you very much!
